name: Python CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout - LATEST VERSION
    - name: Checkout code
      uses: actions/checkout@v4  # Changed from v3
      
    # 2. Setup Python - LATEST VERSION  
    - name: Setup Python
      uses: actions/setup-python@v5  # Changed from v4
      with:
        python-version: '3.9'
        
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    # 4. Run tests
    - name: Run tests
      run: |
        python -m pytest tests/ --junitxml=junit/test-results.xml
        
    # 5. Upload test results - UPDATED VERSION
    - name: Upload test results
      uses: actions/upload-artifact@v4  # Changed from v3
      with:
        name: test-results
        path: junit/test-results.xml